create objects generate function
htmlacademy-javascript/1406535-kekstagram-31 pull request #6
Opened 2024-02-23 19:22 UTC by FoxMalder-coder

2024-02-23 19:24 UTC, FoxMalder-coder commented
Задание 4.16. Больше деталей. Генерируем массив из 25 объектов заданного вида

2024-02-27 14:21 UTC, craz3r requested changes

2024-02-27 14:21 UTC, craz3r commented on js/main.js
> +const comment = () => ({
const getComment

2024-02-27 14:21 UTC, craz3r commented on js/main.js
> +  const array = [];
const photosArray

2024-02-27 14:21 UTC, craz3r commented on js/main.js
> +  return array;
return Array.from({ length: OBJ_QUANTITY }, generatePhoto)

2024-02-27 14:21 UTC, craz3r commented on js/main.js
> +  id: getRandomInt(0, 1000),
Айдишники могут повториться, можно использовать тот же подход, что используется в generateObjects

2024-02-27 14:21 UTC, craz3r commented on js/main.js
> +  for (let i = 0; i < quantity; i++) {
Вместо цикла for лучше использовать метод Array.from() как в 36 строке

2024-02-27 14:21 UTC, craz3r commented on js/main.js
> +    array[i] = {
Вынести получение отдельного объекта с фото в отдельную функцию

2024-02-28 11:07 UTC, merged